Repository subjectsplus/SubjectsPlus, pull requests merged in 2021-06, with the labels that each got.

#1474 fix uses of deprecated implode() signature
  lib/SubjectsPlus/Control/Guide.php
Labels: deprecated, php7.4

#1472 clean up PDO warnings when doing CUD on FAQs
  lib/SubjectsPlus/Control/FAQ.php
Labels: bug

#1450 Don't append erroneous [0] to database URL in Newest Databases box
  subjects/index.php
Labels: bug

#1485 Remove chmod calls from Config.php
  control/edit-config.php
  lib/SubjectsPlus/Control/Config.php
Labels: bug

#1483 Improved Theming Support
  control/includes/functions.php
  subjects/blank-404.php
  subjects/collection.php
  subjects/databases.php
  subjects/faq.php
  subjects/guide.php
  subjects/index.php
  subjects/noguide.php
  subjects/search.php
  subjects/staff.php
  subjects/staff_details.php
  subjects/talkback.php
  subjects/usearch-problem-report.php
  subjects/video.php
Labels: bug, enhancement
